language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt 
  - pip install pytest==4.0.1 pytest-xvfb PyYAML pylint
  - sudo apt-get install libyaml-dev
  - sudo apt-get install python-yaml

# Build and install qt
  - curl -L -O http://sourceforge.net/projects/pyqt/files/sip/sip-4.14.1/sip-4.14.1.tar.gz
  - tar -xf sip-4.14.1.tar.gz
  - cd sip-4.14.1
  - python configure.py
  - make -j 2
  - sudo make install
  - cd ..
  - curl -L -O http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.9.5/PyQt-x11-gpl-4.9.5.tar.gz
  - tar -xf PyQt-x11-gpl-4.9.5.tar.gz
  - cd PyQt-x11-gpl-4.9.5
  - python configure.py --confirm-license
  - make -j 2
  - sudo make install
  - cd ..
script:
  - python -m pytest
  - pylint -E gui
