language: python

python:
  - "2.7"
  - "3.6"

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_wait 20 bash bin/install_pyqt4.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3'* ]]; then travis_wait 20 bash bin/install_pyqt5.sh; fi

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then sudo apt-get install mesa-common-dev; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_retry python -m pip install -r requirements_python2.txt pytest==4.0.1 pytest-xvfb PyYAML pylint; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3'* ]]; then travis_retry pip3 install -r requirements_python3.txt pytest==4.0.1 pytest-xvfb PyYAML pylint; fi

before_script:
  - "export DISPLAY=:99.0"

script:
  - cd test
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_wait 20 python -m pytest; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3'* ]]; then travis_wait 20 python3 -m pytest; fi
  - cd ..
  - pylint -E gui/*py --extension-pkg-whitelist=PyQt5,PyQt4
  - pylint -E gui/bricks --extension-pkg-whitelist=PyQt5,PyQt4
  - pylint -E gui/widgets --extension-pkg-whitelist=PyQt5,PyQt4
  - pylint -E gui/utils --extension-pkg-whitelist=PyQt5,PyQt4
